name: CI
on:
  push:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.rustup/
            target/
          key: rust-${{ hashFiles('Cargo.toml') }}
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --all-features
