name: CI
on:
  push:
    paths:
      - '**.rs'
      - '**Cargo.toml'
      - .github/workflows/ci.yml
      - .github/actions/*/action.yml
    branches: [ '**' ]
    tags-ignore: [ '**' ]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ssh: ["", " -F ssh"]
        tcp: ["", " -F tcp"]
    name: Build with `--no-default-features${{ matrix.ssh }}${{ matrix.tcp }}`
    steps:
      - uses: speelbarrow/checkout-and-setup@v1.3
      - run: cargo build --no-default-features${{ matrix.ssh }}${{ matrix.tcp }}
        
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: speelbarrow/checkout-and-setup@v1.3
      - run: cargo test --all-features
